#!/usr/bin/env sh
set -e

# Create symlink in /usr/local/bin
ln -sf /opt/QuranCLI/QuranCLI /usr/local/bin/qurancli

# Update icon cache
if [ -x /usr/bin/gtk-update-icon-cache ]; then
    gtk-update-icon-cache -q /usr/share/icons/hicolor || true
fi

# Update desktop database
if [ -x /usr/bin/update-desktop-database ]; then
    update-desktop-database -q /usr/share/applications || true
fi

exit 0